import React from 'react';
import Markdown from 'react-markdown';

interface MarkdownRendererProps {
  content: string;
  className?: string;
  isDark?: boolean;
}

// Security helper: sanitize hrefs to prevent javascript: or dangerous protocol execution
function sanitizeUrl(href?: string): string {
  if (!href) return '#';
  const trimmed = href.trim();
  if (
    trimmed.startsWith('http://') ||
    trimmed.startsWith('https://') ||
    trimmed.startsWith('mailto:') ||
    trimmed.startsWith('tel:') ||
    trimmed.startsWith('/') ||
    trimmed.startsWith('#')
  ) {
    return trimmed;
  }
  return '#';
}

/**
 * Normalizes legacy HTML content (generated by the old RichTextEditor) into clean Markdown.
 * - Extracts content from <div> blocks.
 * - Converts <br> to newlines.
 * - Restores basic bold/italic tags to markdown syntax.
 * - Safely strips remaining HTML to expose the underlying Markdown for react-markdown.
 */
export function normalizeHtmlToMarkdown(htmlContent: string): string {
  if (!htmlContent) return '';
  
  // If no block HTML tags are present, it's likely pure Markdown, return as is.
  // We specifically look for tags generated by the old contentEditable WYSIWYG editor.
  const hasLegacyHtml = /<div\b[^>]*>|<br\b[^>]*>|<b\b[^>]*>|<i\b[^>]*>|<strong\b[^>]*>|<em\b[^>]*>/i.test(htmlContent);
  if (!hasLegacyHtml) {
    return htmlContent;
  }

  // Protect Markdown code blocks from having their internal <tags> stripped
  const codeBlocks: string[] = [];
  let protectedContent = htmlContent.replace(/```[\s\S]*?```|`[^`]+`/g, (match) => {
    codeBlocks.push(match);
    return `___CODE_BLOCK_${codeBlocks.length - 1}___`;
  });

  let md = protectedContent
    // Translate rich text basic formatting back to markdown
    .replace(/<b(?:\s+[^>]*)?>(.*?)<\/b>/gi, '**$1**')
    .replace(/<strong(?:\s+[^>]*)?>(.*?)<\/strong>/gi, '**$1**')
    .replace(/<i(?:\s+[^>]*)?>(.*?)<\/i>/gi, '*$1*')
    .replace(/<em(?:\s+[^>]*)?>(.*?)<\/em>/gi, '*$1*')
    // Handle WYSIWYG block mechanics
    .replace(/<div>\s*<br[^>]*>\s*<\/div>/gi, '\n\n') // Empty div with br -> double newline
    .replace(/<\/div>/gi, '\n') // End of div -> newline
    .replace(/<br[^>]*>/gi, '\n') // br -> newline
    // Strip all remaining HTML tags to prevent them from being rendered as text
    .replace(/<[^>]+>/g, '')
    // Clean up non-breaking spaces
    .replace(/&nbsp;/gi, ' ')
    // Limit consecutive newlines to maximum 2 to avoid huge vertical gaps
    .replace(/\n{3,}/g, '\n\n')
    .trim();
    
  // Restore code blocks
  codeBlocks.forEach((block, i) => {
    md = md.replace(`___CODE_BLOCK_${i}___`, block);
  });
    
  return md;
}

export function MarkdownRenderer({ 
  content, 
  className = '', 
  isDark = false 
}: MarkdownRendererProps) {
  if (!content) return null;

  const normalizedContent = normalizeHtmlToMarkdown(content);

  return (
    <div className={`markdown-rendered-body ${className}`}>
      <Markdown
        components={{
          h1: ({ children }) => (
            <h1 className={`text-xl sm:text-2xl font-black tracking-tight mt-6 mb-3 first:mt-0 ${
              isDark ? 'text-white' : 'text-slate-900'
            }`}>
              {children}
            </h1>
          ),
          h2: ({ children }) => (
            <h2 className={`text-lg sm:text-xl font-bold tracking-tight mt-5 mb-2.5 first:mt-0 ${
              isDark ? 'text-slate-100' : 'text-slate-900'
            }`}>
              {children}
            </h2>
          ),
          h3: ({ children }) => (
            <h3 className={`text-base sm:text-lg font-bold tracking-tight mt-4 mb-2 first:mt-0 ${
              isDark ? 'text-slate-200' : 'text-slate-900'
            }`}>
              {children}
            </h3>
          ),
          p: ({ children }) => (
            <p className={`text-sm sm:text-base leading-relaxed mb-3.5 last:mb-0 ${
              isDark ? 'text-slate-200' : 'text-slate-700'
            }`}>
              {children}
            </p>
          ),
          ul: ({ children }) => (
            <ul className={`list-disc pl-5 sm:pl-6 mb-4 space-y-1.5 text-sm sm:text-base ${
              isDark ? 'text-slate-200' : 'text-slate-700'
            }`}>
              {children}
            </ul>
          ),
          ol: ({ children }) => (
            <ol className={`list-decimal pl-5 sm:pl-6 mb-4 space-y-1.5 text-sm sm:text-base ${
              isDark ? 'text-slate-200' : 'text-slate-700'
            }`}>
              {children}
            </ol>
          ),
          li: ({ children }) => (
            <li className="leading-relaxed">
              {children}
            </li>
          ),
          blockquote: ({ children }) => (
            <blockquote className={`border-l-4 pl-4 py-2.5 my-4 rounded-r-2xl italic font-medium text-sm sm:text-base ${
              isDark 
                ? 'border-emerald-500 bg-slate-800/80 text-slate-300' 
                : 'border-emerald-500 bg-emerald-50/60 text-slate-800'
            }`}>
              {children}
            </blockquote>
          ),
          hr: () => (
            <hr className={`my-6 border-t ${isDark ? 'border-slate-800' : 'border-slate-200'}`} />
          ),
          a: ({ href, children }) => {
            const safeHref = sanitizeUrl(href);
            const isExternal = safeHref.startsWith('http');
            return (
              <a
                href={safeHref}
                target={isExternal ? '_blank' : undefined}
                rel={isExternal ? 'noopener noreferrer' : undefined}
                referrerPolicy={isExternal ? 'no-referrer' : undefined}
                className={`font-semibold underline underline-offset-2 transition-colors ${
                  isDark
                    ? 'text-emerald-400 hover:text-emerald-300'
                    : 'text-emerald-600 hover:text-emerald-700'
                }`}
              >
                {children}
              </a>
            );
          },
          code: ({ className: codeClassName, children, ...props }) => {
            const isBlock = Boolean(codeClassName) || (typeof children === 'string' && children.includes('\n'));
            if (!isBlock) {
              return (
                <code
                  className={`px-2 py-0.5 rounded-lg font-mono text-xs sm:text-sm font-semibold border ${
                    isDark
                      ? 'bg-slate-800 text-emerald-300 border-slate-700'
                      : 'bg-slate-100 text-emerald-800 border border-slate-200/80'
                  }`}
                  {...props}
                >
                  {children}
                </code>
              );
            }
            return (
              <code className="font-mono text-xs sm:text-sm" {...props}>
                {children}
              </code>
            );
          },
          pre: ({ children }) => (
            <div className="relative my-4 rounded-2xl overflow-hidden border border-slate-800 shadow-xs bg-slate-900 group">
              <div className="flex items-center justify-between px-4 py-2 bg-slate-950/80 border-b border-slate-800/80 text-[11px] font-mono font-bold text-slate-400">
                <span className="flex items-center gap-1.5 text-emerald-400">
                  <span className="w-2 h-2 rounded-full bg-emerald-500 inline-block" />
                  <span>Exemple de code</span>
                </span>
                <span className="text-slate-500">R / Code</span>
              </div>
              <pre className="p-4 sm:p-5 overflow-x-auto text-xs sm:text-sm font-mono leading-relaxed text-emerald-300 bg-slate-900">
                {children}
              </pre>
            </div>
          )
        }}
      >
        {normalizedContent}
      </Markdown>
    </div>
  );
}

export default MarkdownRenderer;
